name: Run Python Script and Push Changes

permissions:
  contents: write  # Explicitly set permission to write to the repository
  
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  modify-file:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out the repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version

    # Step 3: Install any dependencies (if needed)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have dependencies listed

    # Step 4: Run the Python script to modify a file
    - name: Run Python script
      run: python scraper_app.py  # Your Python script here

    - name: Check if there are changes in the files and push if there are.
    # Check for differences in the file
      run: |
        FILE_TO_CHECK="docs/caudales.json"
        git diff --quiet HEAD -- "$FILE_TO_CHECK"
        # Exit the script if no changes are detected
        if [ $? -eq 0 ]; then
          echo "No changes in $FILE_TO_CHECK. Exiting."
          exit 0
        fi
    # Step 5: Configure Git user and commit changes
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git fetch origin
        git checkout --track origin/caudales
        git add $FILE_TO_CHECK
        echo "Git status after add files"
        git status
        git commit -m "Actualizando caudales..."
        git rebase main
        git push --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token for authentication

# Specify the file to check
FILE_TO_CHECK="docs/caudales.json"

